import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";
import type { ReportSnapshot } from "@/lib/reportEngine";

// Deliberately not a design system — this is a functional cover +
// section/finding/summary layout for Version 1 (§ "Professional PDF
// Generation"). Company branding/logo is a future customization point, not
// wired to any settings UI yet.
const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica", color: "#1e293b" },
  coverTitle: { fontSize: 22, marginBottom: 8, fontFamily: "Helvetica-Bold" },
  coverMeta: { fontSize: 11, marginBottom: 4, color: "#475569" },
  h1: { fontSize: 16, marginBottom: 8, fontFamily: "Helvetica-Bold" },
  h2: { fontSize: 13, marginTop: 14, marginBottom: 4, fontFamily: "Helvetica-Bold" },
  h3: { fontSize: 11, marginTop: 8, marginBottom: 2, fontFamily: "Helvetica-Bold" },
  p: { fontSize: 10, marginBottom: 4, lineHeight: 1.4 },
  label: { fontSize: 9, color: "#64748b" },
  badge: { fontSize: 8, color: "#334155", backgroundColor: "#f1f5f9", padding: 3, marginRight: 4 },
  finding: { marginBottom: 8, paddingBottom: 8, borderBottom: "1 solid #e2e8f0" },
  photoRow: { flexDirection: "row", flexWrap: "wrap", marginTop: 4 },
  photo: { width: 140, height: 105, marginRight: 6, marginBottom: 6, objectFit: "cover" },
  footer: { position: "absolute", bottom: 20, left: 36, right: 36, fontSize: 8, color: "#94a3b8", textAlign: "center" },
  pageNumber: { position: "absolute", bottom: 20, right: 36, fontSize: 8, color: "#94a3b8" },
});

export interface FindingPhoto {
  findingKey: string; // matches "sectionIndex-componentIndex-findingIndex"
  dataUri: string;
  caption: string | null;
}

export function ReportDocument({ snapshot, photosByFinding }: { snapshot: ReportSnapshot; photosByFinding: Map<string, FindingPhoto[]> }) {
  const inspectionDate = snapshot.inspectionDate ? new Date(snapshot.inspectionDate).toLocaleDateString() : "Not recorded";

  return (
    <Document title={`${snapshot.reportNumber} — Inspection Report`}>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.coverTitle}>{snapshot.title || "Property Inspection Report"}</Text>
        <Text style={styles.coverMeta}>Report Number: {snapshot.reportNumber}</Text>
        <Text style={styles.coverMeta}>
          {snapshot.property.addressLine1}
          {snapshot.property.addressLine2 ? `, ${snapshot.property.addressLine2}` : ""}, {snapshot.property.city},{" "}
          {snapshot.property.state} {snapshot.property.zip}
        </Text>
        <Text style={styles.coverMeta}>Inspection Date: {inspectionDate}</Text>
        <Text style={styles.coverMeta}>Prepared For: {snapshot.customerName || "Not recorded"}</Text>
        <Text style={styles.coverMeta}>Inspector: {snapshot.inspectorName || "Not recorded"}</Text>
        <Text style={styles.coverMeta}>
          Version {snapshot.versionNumber} — Finalized {new Date(snapshot.finalizedAt).toLocaleString()}
        </Text>
        {snapshot.reasonForRevision && (
          <Text style={styles.coverMeta}>Reason for revision: {snapshot.reasonForRevision}</Text>
        )}

        {snapshot.introduction && (
          <>
            <Text style={styles.h2}>Introduction</Text>
            <Text style={styles.p}>{snapshot.introduction}</Text>
          </>
        )}
        {snapshot.scope && (
          <>
            <Text style={styles.h2}>Scope</Text>
            <Text style={styles.p}>{snapshot.scope}</Text>
          </>
        )}
        {snapshot.limitations && (
          <>
            <Text style={styles.h2}>Limitations</Text>
            <Text style={styles.p}>{snapshot.limitations}</Text>
          </>
        )}

        <Text style={styles.footer}>{snapshot.footer || "Generated by Inspection CRM — not an engineering, legal, or code-compliance determination."}</Text>
        <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
      </Page>

      {snapshot.summary.length > 0 && (
        <Page size="LETTER" style={styles.page}>
          <Text style={styles.h1}>Summary</Text>
          {Object.entries(groupBy(snapshot.summary, (s) => s.groupLabel)).map(([group, items]) => (
            <View key={group}>
              <Text style={styles.h2}>{group}</Text>
              {items.map((item, idx) => {
                const finding = findFindingById(snapshot, item.findingId);
                if (!finding) return null;
                return (
                  <Text key={idx} style={styles.p}>
                    • {finding.title}
                  </Text>
                );
              })}
            </View>
          ))}
          <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
        </Page>
      )}

      {snapshot.sections.map((section, sIdx) => (
        <Page key={sIdx} size="LETTER" style={styles.page} wrap>
          <Text style={styles.h1}>{section.name}</Text>
          {section.notApplicable ? (
            <Text style={styles.p}>Not applicable to this property.</Text>
          ) : (
            section.components.map((component, cIdx) => (
              <View key={cIdx} wrap={false}>
                <Text style={styles.h3}>
                  {component.name} — <Text style={styles.label}>{component.inspectionStatus.replace(/_/g, " ")}</Text>
                </Text>
                {component.limitationNote && <Text style={styles.p}>Note: {component.limitationNote}</Text>}
                {component.notes && <Text style={styles.p}>{component.notes}</Text>}
                {component.findings.map((finding, fIdx) => {
                  const key = `${sIdx}-${cIdx}-${fIdx}`;
                  const photos = photosByFinding.get(key) ?? [];
                  return (
                    <View key={fIdx} style={styles.finding}>
                      <Text style={styles.h3}>{finding.title}</Text>
                      <View style={{ flexDirection: "row", marginBottom: 2 }}>
                        {finding.category && <Text style={styles.badge}>{finding.category}</Text>}
                        {finding.safetyRelated && <Text style={styles.badge}>Safety</Text>}
                        {finding.repairRecommended && <Text style={styles.badge}>Repair Recommended</Text>}
                        {finding.monitor && <Text style={styles.badge}>Monitor</Text>}
                        {finding.furtherEvaluation && <Text style={styles.badge}>Further Evaluation</Text>}
                      </View>
                      {finding.location && <Text style={styles.label}>Location: {finding.location}</Text>}
                      <Text style={styles.p}>{finding.description}</Text>
                      {finding.recommendation && (
                        <Text style={styles.p}>Recommendation: {finding.recommendation}</Text>
                      )}
                      {photos.length > 0 && (
                        <View style={styles.photoRow}>
                          {photos.map((photo, pIdx) => (
                            <View key={pIdx}>
                              <Image src={photo.dataUri} style={styles.photo} />
                              {photo.caption && <Text style={styles.label}>{photo.caption}</Text>}
                            </View>
                          ))}
                        </View>
                      )}
                    </View>
                  );
                })}
              </View>
            ))
          )}
          <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
        </Page>
      ))}
    </Document>
  );
}

function groupBy<T>(items: T[], keyFn: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of items) {
    const key = keyFn(item);
    (result[key] ??= []).push(item);
  }
  return result;
}

function findFindingById(snapshot: ReportSnapshot, findingId: string) {
  for (const section of snapshot.sections) {
    for (const component of section.components) {
      for (const finding of component.findings) {
        if (finding.id === findingId) return finding;
      }
    }
  }
  return null;
}
